In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

In [26]:
rates = pd.read_csv('./InterestRates.csv')
#rates.info()
rates['pricedate2'] = pd.to_datetime(rates.pricedate, format='%Y-%m-%d', errors='ignore')
#print (rates.dtypes)

#rates.head()
#rates.maturity.unique()

pricedate             object
maturity              object
bidrate              float64
pricedate2    datetime64[ns]
dtype: object

In [28]:
NGvols20 = pd.read_csv('./NG_ImpliedVols2020.csv')
#NGvols20.info()
NGvols20['begtime'] = pd.to_datetime(NGvols20.begtime, format='%Y-%m-%d', errors='ignore')
NGvols20['volatilitydate'] = pd.to_datetime(NGvols20.volatilitydate, format='%Y-%m-%d', errors='ignore')
NGvols20['duration'] = NGvols20.begtime - NGvols20.volatilitydate;
NGvols20.head()

,volatilityindex,volatilitydate,strikeprice,begtime,volatility,duration
0,V_NYMEX Natural Gas,2020-03-09,2.65,2020-11-01,0.336,237 days
1,V_NYMEX Natural Gas,2020-03-09,2.70,2020-11-01,0.336,237 days
2,V_NYMEX Natural Gas,2020-03-09,2.75,2020-11-01,0.336,237 days
3,V_NYMEX Natural Gas,2020-03-09,2.80,2020-11-01,0.336,237 days
4,V_NYMEX Natural Gas,2020-03-09,2.85,2020-11-01,0.337,237 days

In [ ]:
NGvols20.head()

In [4]:
NGvols21 = pd.read_csv('./NG_ImpliedVols2021.csv')
NGvols21.info()
NGvols21.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59166 entries, 0 to 59165
Data columns (total 5 columns):
volatilityindex    59166 non-null object
volatilitydate     59166 non-null object
strikeprice        59166 non-null float64
begtime            59166 non-null object
volatility         59166 non-null float64
dtypes: float64(2), object(3)
memory usage: 2.3+ MB

       volatilityindex volatilitydate  strikeprice     begtime  volatility
0  V_NYMEX Natural Gas     2020-03-10         1.90  2021-11-01       0.205
1  V_NYMEX Natural Gas     2020-03-10         1.95  2021-11-01       0.204
2  V_NYMEX Natural Gas     2020-03-10         2.00  2021-11-01       0.203
3  V_NYMEX Natural Gas     2020-03-10         2.05  2021-11-01       0.201
4  V_NYMEX Natural Gas     2020-03-10         2.10  2021-11-01       0.200

In [5]:
NGvols22 = pd.read_csv('./NG_ImpliedVols2022.csv')
NGvols22.info()
NGvols22.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60480 entries, 0 to 60479
Data columns (total 5 columns):
volatilityindex    60480 non-null object
volatilitydate     60480 non-null object
strikeprice        60480 non-null float64
begtime            60480 non-null object
volatility         60480 non-null float64
dtypes: float64(2), object(3)
memory usage: 2.3+ MB

       volatilityindex volatilitydate  strikeprice     begtime  volatility
0  V_NYMEX Natural Gas     2020-03-10         1.13  2022-01-01       0.175
1  V_NYMEX Natural Gas     2020-03-10         1.18  2022-01-01       0.179
2  V_NYMEX Natural Gas     2020-03-10         1.23  2022-01-01       0.182
3  V_NYMEX Natural Gas     2020-03-10         1.28  2022-01-01       0.185
4  V_NYMEX Natural Gas     2020-03-10         1.33  2022-01-01       0.188

In [11]:
prices = pd.read_csv('./PricesFile1.csv')
prices.info()
prices.head()
#prices.priceindex.unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6130 entries, 0 to 6129
Data columns (total 4 columns):
priceindex    6130 non-null object
pricedate     6130 non-null object
delivdate     6130 non-null object
price         6130 non-null float64
dtypes: float64(1), object(3)
memory usage: 191.6+ KB

                      priceindex   pricedate   delivdate   price
0      AECO NIT MONTHLY (7A) US$  2020-03-01  2020-03-01  1.3219
1      AECO NIT MONTHLY (7A) US$  2020-04-01  2020-04-01  1.2421
2      AECO NIT MONTHLY (7A) US$  2020-05-01  2020-05-01  1.3385
3  AECO NIT MONTHLY (7A) US$ FWD  2020-03-02  2020-04-01 -0.5140
4  AECO NIT MONTHLY (7A) US$ FWD  2020-03-02  2020-05-01 -0.6160

In [7]:
WTIvols20 = pd.read_csv('./WTI_ImpliedVols2020.csv')
WTIvols20.info()
WTIvols20.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32968 entries, 0 to 32967
Data columns (total 5 columns):
volatilityindex    32968 non-null object
volatilitydate     32968 non-null object
strikeprice        32968 non-null float64
begtime            32968 non-null object
volatility         32968 non-null float64
dtypes: float64(2), object(3)
memory usage: 1.3+ MB

           volatilityindex volatilitydate  strikeprice     begtime  volatility
0  V_WTI NYMEX LIGHT SWEET     2020-03-06         25.0  2020-11-01       0.475
1  V_WTI NYMEX LIGHT SWEET     2020-03-06         25.5  2020-11-01       0.471
2  V_WTI NYMEX LIGHT SWEET     2020-03-06         26.0  2020-11-01       0.467
3  V_WTI NYMEX LIGHT SWEET     2020-03-06         26.5  2020-11-01       0.463
4  V_WTI NYMEX LIGHT SWEET     2020-03-06         27.0  2020-11-01       0.458

In [8]:
WTIvols21 = pd.read_csv('./WTI_ImpliedVols2021.csv')
WTIvols21.info()
WTIvols21.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35134 entries, 0 to 35133
Data columns (total 5 columns):
volatilityindex    35134 non-null object
volatilitydate     35134 non-null object
strikeprice        35134 non-null float64
begtime            35134 non-null object
volatility         35134 non-null float64
dtypes: float64(2), object(3)
memory usage: 1.3+ MB

           volatilityindex volatilitydate  strikeprice     begtime  volatility
0  V_WTI NYMEX LIGHT SWEET     2020-03-06         27.0  2021-01-01       0.423
1  V_WTI NYMEX LIGHT SWEET     2020-03-06         27.5  2021-01-01       0.419
2  V_WTI NYMEX LIGHT SWEET     2020-03-06         28.0  2021-01-01       0.415
3  V_WTI NYMEX LIGHT SWEET     2020-03-06         28.5  2021-01-01       0.411
4  V_WTI NYMEX LIGHT SWEET     2020-03-06         29.0  2021-01-01       0.407

In [9]:
WTIvols22 = pd.read_csv('./WTI_ImpliedVols2022.csv')
WTIvols22.info()
WTIvols22.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9639 entries, 0 to 9638
Data columns (total 5 columns):
volatilityindex    9639 non-null object
volatilitydate     9639 non-null object
strikeprice        9639 non-null float64
begtime            9639 non-null object
volatility         9639 non-null float64
dtypes: float64(2), object(3)
memory usage: 376.6+ KB

           volatilityindex volatilitydate  strikeprice     begtime  volatility
0  V_WTI NYMEX LIGHT SWEET     2020-03-06         31.5  2022-06-01       0.265
1  V_WTI NYMEX LIGHT SWEET     2020-03-06         32.0  2022-06-01       0.265
2  V_WTI NYMEX LIGHT SWEET     2020-03-06         32.5  2022-06-01       0.265
3  V_WTI NYMEX LIGHT SWEET     2020-03-06         33.0  2022-06-01       0.265
4  V_WTI NYMEX LIGHT SWEET     2020-03-06         33.5  2022-06-01       0.264